name: main-CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6.1.0

    - name: Set up Python
      uses: actions/setup-python@v7.0.0
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run bandit and save the report
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
        name: Bandit findings
        path: bandit-report.json
        
  image_scan:
    name: Docker image scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6.1.0

    - name: Create Docker daemon configuration
      run: |
       sudo mkdir -p /etc/docker
       echo '{}' | sudo tee /etc/docker/daemon.json

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '24.0'

    - name: Build Docker image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Docker scout scan
      run: |
        curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
        docker scout quickview myapp:latest
        docker scout cves myapp:latest --output scout-report.sarif

    - name: Upload Artifact
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
        name: Scout findings
        path: scout-report.sarif
  
   
        
      
