name: main-CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6.1.0

    - name: Set up Python
      uses: actions/setup-python@v7.0.0
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run bandit and save the report
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
        name: Bandit findings
        path: bandit-report.json
        
      
